services:
  connect:
    build: ./IYLTDSU.Signalling.OnConnect/.
    ports:
      - 5006:5006
  disconnect: 
    build: ./IYLTDSU.Signalling.OnDisconnect/.
    ports: 
      - 5005:5005
  message:
    build: ./IYLTDSU.Signalling.OnMessage/.
    ports: 
      - 5004:5004