name: "Build, test, deploy functions"
on:
  push:
    branches: [ main ]
jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build with dotnet
        run: dotnet build --configuration Release

  Test: 
    runs-on: ubuntu-latest
    needs: Build
    strategy:
      matrix:
        testFunctionName: 
         - 'EnsureOnlyValidIdentifierCanConnect'
         - 'EnsureOnlyValidIdentifierCanDisconnect'
         - 'EnsureOnlyValidIdentifierCanSendMessage'
         - 'EnsureOnlyValidIdentifierCanQueueX01'
         - 'EnsureOnlyValidIdentifierCanScoreX01'
         - 'EnsureOnlyValidIdentifierCanCreateRoom'
         - 'EnsureOnlyValidIdentifierCanJoinRoom'
         - 'EnsureOnlyValidIdentifierCanLeaveRoom'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Run tests
        run: dotnet test --filter Name=${{ matrix.testFunctionName }}
        id: function-test
      - name: action-slack
        if: failure() && steps.function-test.outcome != 'success'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ steps.function-test.outcome }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  Publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: Test
    strategy:
      matrix:
        functionName: 
         - 'IYLTDSU-Signalling-OnConnect'
         - 'IYLTDSU-Signalling-OnDisconnect'
         - 'IYLTDSU-Signalling-OnDefault'
         - 'IYLTDSU-Rooms-OnCreate'
         - 'IYLTDSU-Rooms-OnJoin'
         - 'IYLTDSU-Rooms-OnLeave'
         - 'IYLTDSU-Games-X01-OnScore'
         - 'IYLTDSU-Games-X01-OnQueue'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Install Amazon.Lambda.Tools
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy function
        working-directory: ${{ matrix.functionName }}
        run: |
          dotnet lambda deploy-function --function-name ${{ matrix.functionName }} -frun dotnet6 --region eu-west-1
        id: function-deploy
      - name: action-slack
        if: failure() && steps.function-deploy.outcome != 'success'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ steps.function-deploy.outcome }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
