name: "Run CDK diff"

on:
  [pull_request]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  cdk-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build tag dockerfile
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./IYLTDSU.Signalling.Infrastructure/Dockerfile
          tags: local/websocketsinfra:latest
          push: false

      - name: Run cdk diff in Docker
        id: diff
        run: | 
          echo "WARREN'S TEST OUTPUT"

      - name: Comment on PR
        uses: actions/github-script@0.9.0
        env:
          DIFF: "CDK\n${{ steps.diff.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const environmentString = `Environment: Development`;
            const output = `#### ${environmentString}
            <details><summary>Show Diff</summary>
            \`\`\`${process.env.DIFF}\`\`\`
            </details>
            *Pusher: Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            const comments = await github.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });
            const planComment = comments.data.find(c => c.body.includes(environmentString));
            if (planComment) {
              await github.issues.updateComment({
                issue_number: context.issue.number,
                comment_id: planComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            } else {
              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            }