name: "Comment a Plan on a PR"

on:
  [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  cdk-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./IYLTDSU.Signalling.Infrastructure/Dockerfile
          tags: local/websocketsinfra:latest
          push: false
      - name: Run
        run: | 
          docker run -e AWS_REGION=${{ secrets.AWS_REGION }} -e AWS_ACCOUNT=${{ secrets.AWS_ACCOUNT }} -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} local/websocketsinfra:latest >> $GITHUB_STEP_SUMMARY
          echo "CDK_DIFF_RESULT=$GITHUB_STEP_SUMMARY" >> $GITHUB_ENV
      - name: Comment cdk diff
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
          message: ${{ env.CDK_DIFF_RESULT }}
